depromeet/15th-team3-FE

.github/CODEOWNERS
.github/workflows/auto-merge.yml

- `approve`를 하나 받으면: auto merge가 됩니다.
- 기본적으로 dev 브랜치로 머지되며
- `main merge` 라벨을 선택하면 main 브랜치로 자동 머지가 됩니다.
- `no auto merge` 라벨을 붙이면
- approve가 존재해도 머지 되지 않습니다.
- 중간에 라벨을 떼면 오토 머지 워크플로우가 동작됩니다.
- `auto approve` 라벨을 붙이면
- 공용 계정이 나타나 approve → 오토 머지 워크 플로우가 동작합니다.
이거 테스트 필요해요 🚨 
gpt야 고맙다

chore(*): auto-merge workflow 추가

---

.github/workflows/slack-notification.yml

chore(*): workflow slack notification 추가

---

.github/workflows/slack-notification.yml

- PR 텍스트를 변경하였습니다.
- Comment에서 언급하는 경우 Slack에 알림이 가도록 구현하였습니다.
https://www.notion.so/depromeet/workflow-2fd7dee2874546a1ae21e97a0e2bb015?pvs=4

fix(*): slack notification 메시지 수정

---

.github/workflows/deploy.yml
package.json
pnpm-lock.yaml
tools/build.sh
turbo.json

feat: vercel 배포 CI/CD

---

.vscode/settings.json
package.json
pnpm-lock.yaml
turbo/generators/config.ts
turbo/generators/templates/eslintrc.hbs
turbo/generators/templates/package.hbs
turbo/generators/templates/tsconfig.hbs

packages/core 하위디렉토리에 package-init이 가능하도록 설정하였습니다.
https://github.com/depromeet/15th-team3-FE/assets/92032081/b50c2349-86c0-4735-8245-90644935bb8a

chore(*): script init package

---

packages/core/sds/package.json
packages/core/sds/src/index.ts
packages/core/sds/src/theme/borderRadius.ts
packages/core/sds/src/theme/colors.ts
packages/core/sds/src/theme/index.ts
packages/core/sds/src/theme/opacity.ts
packages/core/sds/src/theme/shadow.ts

현재 fix된 디자인 토큰을 우선 반영합니다.
```tsx
// Usage
import { colors } from '@sambad/sds/theme'
<div style={{ color: colors.grey500 }} />
```
- [figma](https://www.figma.com/design/K0vbFsWUNzQXl5NRGra2m9/[DPM]-3팀🧑‍🚀?node-id=766-1454&t=ZMtrv2FM886tL5Tm-11)

chore(sds): 기본 디자인 토큰 세팅

---

.husky/post-merge
package.json

* 모든 브랜치에 대해서 pull 시 pnpm install 수행
* postinstall 스크립트(husky install)는 확인해본 결과 목표한 것과는 관련이 없어 제거함
이제 모든 브랜치를 대상으로 git pull 시 pnpm install을 수행합니다.
이렇게 변경한 이유는 디버깅을 할 수 있는 환경을 마련하기가 너무 까다로워서 (패키지 의존성 변경 -> origin main에 반영 -> 다시 내 로컬로 pull) 입니다.
의존성 변경이 없다면 pnpm install을 실행해도 1초 이내로 마무리 되므로, 그리고 git pull을 자주 하지는 않으므로, 위와 같이 변경했습니다.

chore(*): post-merge 스크립트 변경

---

packages/core/sds/package.json
packages/core/sds/src/components/Typography/Txt.tsx
packages/core/sds/src/components/Typography/index.ts
packages/core/sds/src/components/Typography/styles.ts
packages/core/sds/src/components/Typography/types.ts
packages/core/sds/src/components/index.ts

[가이드](https://www.figma.com/design/K0vbFsWUNzQXl5NRGra2m9/%5BDPM%5D-3%ED%8C%80%F0%9F%A7%91%E2%80%8D%F0%9F%9A%80?node-id=2531-51928&t=r2Chxfr0bm0yDqnB-11)에 맞춰 Txt 컴포넌트를 추가합니다.
```tsx
// Usage
<Txt as="p" typography="title1" fontWeight="regular" color={colors.primary200}>삼봤뜨</Txt>
```
잘 확인하시고 default 값을 사용하게 될 때 prop을 넘기지 않도록 합시다 !
- typography: `'body2'` (*커스텀 가능)
- color: `colors.grey700` (*커스텀 가능)
- fontWeight: `typography prop을 따라가도록` (*커스텀 가능)
- fontSize: `typography prop을 따라가도록`
- lineHeight: `typography prop을 따라가도록`
color랑 fontWeight는 사용처에서 커스텀이 필요할 경우가 많아서 커스텀 가능하도록 열어두었습니다~
(fontWeight는 .. 호버 한다던가 select 되었을 때 bold 처리하는 경우가 많은 것 같아요)
다형성 컴포넌트로 만드려다가 실패해서.. 우선은 `as` prop은 먹지만 타입은 매핑되지 않습니다...
기본적인 것들만 사용한다면 당장은 크게 문제 없을 거 같아요!
리소스 남을 때 다시 디깅해보겠습니다 …

feat(sds): Txt 컴포넌트 추가

---

packages/core/sds/src/components/Typography/Txt.tsx

Txt 컴포넌트의 fontWeight prop이 동작하지 않는 문제를 해결합니다.
|:--:|:--:|
| ![image](https://github.com/user-attachments/assets/b0fa459c-69dc-4315-8579-353a2285f477) |  ![image](https://github.com/user-attachments/assets/8d0ea622-8c4d-4fc8-ada7-eea02b8addb0) |

fix(sds): Txt 컴포넌트 fontWeight 오류

---

packages/core/sds/src/components/TextButton/TextButton.tsx
packages/core/sds/src/components/TextButton/index.ts
packages/core/sds/src/components/TextButton/styles.ts
packages/core/sds/src/components/TextButton/types.ts
packages/core/sds/src/components/index.ts

텍스트 형태의 버튼 기능을 사용해야 할 때 활용될 컴포넌트입니다.
```tsx
<TextButton variant="normal | underline | arrow" color={colors.grey200}>TEXTBUTTON</TextButton>
```
underline
arrow
normal (default)
button 엘리먼트 속성을 사용할 수 있고, hover시 `cursor: 'pointer'`로 구분감이 있으며, 여러 variant를 제공해요

feat(sds): TextButton 구현

---

packages/core/eslint-config/base.js
packages/core/types-utils/tanstack/index.d.ts
packages/core/typescript-config/base.json

핫픽스입니다.global로 선언하니 의존성관리가 힘들어져서, push할때, 정확히 찾기가 힘드네요
강제로 머지하겠습니다.

fix: 커스텀 useQueryOPtions global declare 해제

---

packages/core/types-utils/package.json
packages/core/types-utils/tanstack/index.d.ts
pnpm-lock.yaml

하나의 타입을 제네릭의 2개의 인자에 동일하게 넘겨주고 있어서, 하나의 인자로 전달해도 문제 없도록 리팩터링 했어요
👇 기존 코드에서 하나의 인자만 넘겨주었을 때
```
options: UseQueryOptionsExcludedQueryKey<FooResponse>
```

refactor(types-utils): UseQueryOptionsWithAxios 유틸 타입 추가

---

packages/core/sds/src/components/Button/Button.tsx
packages/core/sds/src/components/Button/styles.ts

- font-weight fix (medium -> semibold)
- hover 컬러 추가
- `leftDecor` 스펙 추가
```tsx
<Button leftDecor={<Icon name="foo" />}>BUTTON</Button>
```
^ 와 같이 사용하시면 `여백`, `사이즈`, `컬러`가 버튼 스펙에 맞게 적용됩니다.
https://github.com/user-attachments/assets/a96fe3f0-fa98-4ef2-946d-c8f3a8a20079
sds에서는 악세서리류 네이밍을 `Decor`을 사용하려고 합니다 ~!

feat(sds): Button hover 컬러 설정 및 leftDecor 스펙 추가

---

packages/core/sds/src/components/Loader/Loader.tsx
packages/core/sds/src/components/Loader/constants.ts
packages/core/sds/src/components/Loader/index.ts
packages/core/sds/src/components/Loader/styles.ts
packages/core/sds/src/components/Loader/types.ts
packages/core/sds/src/components/index.ts

- mode
- `dim`:  먹은 회색 배경이 깔립니다. (사용처에서 상위에 position: relative 해주게 되면 fit하게 들어갑니다.)
- `transparent` : 배경 없이 로더만 보입니다.
```tsx
<Loader mode="dim | transparent" />
```
- **풀페이지** 혹은 **일부 컨텐츠 영역 중앙**에 쓰일 목적의 로더라서 w, h 100%로 씌워져 있어요.
- 사용성에 따라 로더 알맹이만 따로 제공할 생각도 있어요.
https://github.com/user-attachments/assets/ec8ad685-dc6d-4c52-89cb-b45735d139c7

feat(sds): Loader 컴포넌트 추가

---

packages/core/sds/src/components/Skeleton/Paragraphs.tsx
packages/core/sds/src/components/Skeleton/Skeleton.tsx
packages/core/sds/src/components/Skeleton/index.ts
packages/core/sds/src/components/Skeleton/styles.ts
packages/core/sds/src/components/index.ts

- `Skeleton` 컴포넌트를 추가합니다.
```tsx
// 기본적으로 100%입니다.
<Skeleton width?={number} height?={number} />
// 기본적으로 count = 3 입니다.
<Skeleton.Paragraphs count?={number} />
```
- 텍스트를 불러올 자리에 사용하기 편하도록 추가했어요.
- `count`라는 prop을 통해 더 많은 줄을 표시할 수 있어요.
https://github.com/user-attachments/assets/4eb4f0a1-b9a0-4ef7-ab34-94a189c37d84

feat(sds): Skeleton 컴포넌트 추가

---

packages/core/sds/src/components/Skeleton/Paragraphs.tsx

스켈레톤 Paragraphs 에 ref가 누락되어있고, 타입이 중복으로 참조되어서 제거했습니다.

fix(sds): Skeleton.Paragraphs 누락된 ref 추가 및 타입 수정

---

packages/web-domains/src/about-me/features/containers/AnsweredQuestionsContainer.tsx
packages/web-domains/src/about-me/features/containers/styles.ts

제곧내..
[QA](https://www.notion.so/depromeet/padding-4px-23edbcd606d143e5b6b51d4cca83d259?pvs=4)

fix(web-domains): about 페이지에서 answers 리스트 중 comment가 없을 경우 렌더링하지 않도록 수정

---

packages/web-domains/src/about-me/common/apis/mutates/useCreateHandWavings.ts
packages/web-domains/src/about-me/common/apis/queries/useGetHandWavingsStatus.ts
packages/web-domains/src/about-me/common/apis/schema/HandWavingStatusResponse.ts
packages/web-domains/src/about-me/features/containers/ScreenContainer.tsx
packages/web-domains/src/about-me/features/containers/styles.ts
packages/web-domains/src/about-me/features/hooks/useGetFirstMeetingId.ts

알림 탭에서 손 흔들기 응답 개발되고 버그 나오면 바로바로 픽스하겠습니닷
https://github.com/user-attachments/assets/c24525f6-3d20-4d59-aacd-11d64e62d9f3

feat(web-domains): about 페이지 손 흔들기 기능 추가

---

packages/core/css-utils/src/getCssVar.ts
packages/core/css-utils/src/index.ts
packages/core/sds/package.json
packages/core/sds/src/components/Checkbox/Checkbox.tsx
packages/core/sds/src/components/Checkbox/index.ts
packages/core/sds/src/components/Checkbox/styles.ts
packages/core/sds/src/components/Icon/assets/Check.tsx
packages/core/sds/src/components/Icon/constants.ts
packages/core/sds/src/components/index.ts
pnpm-lock.yaml

Checkbox 컴포넌트를 추가합니다. 시간이 부족해 Group은 추후에 개발하려고 합니다.
https://github.com/user-attachments/assets/73159e3f-c496-46ef-9045-93fe82aa0267

feat(sds, css-utils): Checkbox 컴포넌트 추가

---

packages/web-domains/src/new-meeting/features/get-meeting-info/components/Checkbox/Checkbox.tsx
packages/web-domains/src/new-meeting/features/get-meeting-info/components/Checkbox/CheckboxLabel.tsx
packages/web-domains/src/new-meeting/features/get-meeting-info/components/Checkbox/styles.ts
packages/web-domains/src/new-meeting/features/get-meeting-info/components/GetMeetingInfo/GetMeetingInfo.tsx
packages/web-domains/src/user/features/get-user-info/components/Checkbox/Checkbox.tsx
packages/web-domains/src/user/features/get-user-info/components/Checkbox/CheckboxLabel.tsx
packages/web-domains/src/user/features/get-user-info/components/Checkbox/styles.ts
packages/web-domains/src/user/features/get-user-info/components/Form/BasicInfoForm.tsx
packages/web-domains/src/user/features/get-user-info/components/Form/ExtraInfoForm.tsx
packages/web-domains/src/user/features/get-user-info/components/Form/HobbiesInfoForm.tsx
packages/web-domains/src/user/features/get-user-info/components/Form/IntroInfoForm.tsx
packages/web-domains/src/user/features/get-user-info/components/Form/MbtiInfoForm.tsx
packages/web-domains/src/user/features/get-user-info/components/Radio/Radio.tsx
packages/web-domains/src/user/features/get-user-info/components/Radio/RadioLabel.tsx
packages/web-domains/src/user/features/get-user-info/components/Radio/styles.ts
packages/web-domains/src/user/features/oauth-kakao-login/components/KakaoLoginButton/KakaoLoginButton.tsx

- UI QA진행 완료했습니다.
- sds 버튼에서 기존 hover스타일을 웹에서만 적용되도록 수정하였습니다.

fix(web-domains, sds): 유저, 모임 생성, 모임 참여 1차 QA 수정

---

packages/web-domains/src/relay-question/features/share-group/types/index.ts
packages/web-domains/src/relay-question/features/share-next-questioner/containers/ShareNextQuestionerContainer/ShareNextQuestionerContainer.tsx

* 다음 질문인에게 공유하기 페이지에서 카카오톡 공유하기 모달 기능을 사용했을 때, 다음 질문인이 아닌 현재 질문인이 표시되는 오류 수정
* 다음 질문인에게 공유하기 페이지에서 하단 버튼 size 오지정 스타일 오류 해결

fix(web-domains): 다음 질문인 카카오톡 공유하기 오지정 오류 해결

---

packages/web-domains/src/home/features/my-profile/containers/MyprofileContainer.tsx

fix: 자기소개 수정시 릴레이 질문만 노출되도록 수정

---

packages/core/sds/src/components/TextButton/TextButton.tsx
packages/core/sds/src/components/TextButton/styles.ts
packages/core/sds/src/components/Typography/Txt.tsx
packages/core/sds/src/components/Typography/styles.ts

사용처에서 스타일 오버라이드 시 기본 스타일이 우선순위가 더 높아(style로 스타일 주입) 오버라이드 시 불필요한 우선순위를 높여주는 작업을 해야 했습니다. 
이를 css variable과 css prop으로 처리하여 우선순위를 낮춥니다.

fix(sds): Txt, TextButton 컴포넌트 기본 스타일은 스타일 오버라이드 시 우선순위가 높이 올라오지 않도록 css 처리

---

packages/web-domains/src/home/common/apis/schema/Notification.schema.ts
packages/web-domains/src/home/features/notification/components/NotificationList.tsx
packages/web-domains/src/home/features/notification/containers/AlarmListContainer.tsx
packages/web-domains/src/home/features/notification/services/useAlarmListService.ts

* 알림탭에서 알림이 비어 있을 때 EmptyView
* notification.additionalData null case 대응

feat(web-domains/home): 알림탭에서 알림이 비어 있을 때 EmptyView 및 notification.additionalData null case 대응

---

packages/web-domains/src/relay-question/features/share-group/containers/CurrentRelayQuestionCountContainer/CurrentRelayQuestionCountContainer.tsx

fix(relay-question): 그룹 공유 클로징 페이지에서 모임 이름 대신 '삼봤드의 모험' 상수값으로 고정되어 있던 오류 수정

---

packages/web-domains/src/about-me/common/apis/schema/MeetingMemberResponse.ts
packages/web-domains/src/about-me/features/components/Profile/Profile.tsx
packages/web-domains/src/about-me/features/containers/AboutMeContainer.tsx
packages/web-domains/src/home/features/my-profile/components/AboutMe.tsx

스키마를 수정하고 optional 데이터에 대해 대응하는 코드를 추가합니다.

fix(web-domains): 자기소개 정보 중 optional 데이터 대응

---

packages/web-domains/src/answer/features/answer-closing/containers/AnswerClosingContainer.tsx
packages/web-domains/src/answer/features/answer-closing/services/useAnswerClosingService.ts
packages/web-domains/src/common/components/KakaoShare/generateKakaoShare.utils.ts
packages/web-domains/src/home/features/gather-member/containers/GatherMemberProfileListContainer.tsx
packages/web-domains/src/home/features/gather-member/services/useGatherMemberProfileListService.tsx
packages/web-domains/src/relay-question/features/select-relay-question/components/Question/Question.tsx
packages/web-domains/src/relay-question/features/share-group/containers/CurrentRelayQuestionCountContainer/CurrentRelayQuestionCountContainer.tsx

refactor(web-domains): 카카오톡 공유하기 모달 이미지 및 멘트 등 각종 이슈 해결

---

packages/web-domains/src/answer/features/progressing-question/containers/ProgressingQuestionContainer.tsx
packages/web-domains/src/answer/features/progressing-question/services/useProgressingQuestionService.tsx
packages/web-domains/src/answer/features/top-bar/containers/TopBarContainer.tsx
packages/web-domains/src/common/components/ActionBar/ActionBar.tsx
packages/web-domains/src/home/common/apis/mutations/useUpdateLastMeeting.ts

fix: 답변 페이지 만료 대응

---

packages/web-domains/src/answer/features/comment/containers/CommentContainer.tsx
packages/web-domains/src/answer/features/comment/services/useCommentService.tsx
packages/web-domains/src/answer/features/floating-button/components/CommentButton.tsx
packages/web-domains/src/relay-question/features/select-relay-question/components/Questioner/Questioner.tsx
packages/web-domains/src/relay-question/features/select-relay-question/components/QuestionerDetail/QuestionerDetail.tsx
packages/web-domains/src/relay-question/features/select-relay-question/containers/RandomPickContainer/RandomPickContainer.tsx
packages/web-domains/src/relay-question/features/select-relay-question/hooks/mutations/usePostRelayQuestionInfo.ts

fix(web-domains): 질문 답변 완료, 코멘트 답변 완료, 질문인 선택 post 요청 시 버튼 로딩 처리 

---

packages/web-domains/src/answer/features/comment/components/Comment.tsx
packages/web-domains/src/answer/features/comment/components/CommentInput.tsx
packages/web-domains/src/new-meeting/features/get-meeting-info/components/TextField/TextField.tsx
packages/web-domains/src/user/features/get-user-info/components/Form/ExtraInfoForm.tsx
packages/web-domains/src/user/features/get-user-info/components/Form/IntroInfoForm.tsx
packages/web-domains/src/user/features/get-user-info/components/TextInput/TextArea.tsx
packages/web-domains/src/user/features/get-user-info/components/TextInput/TextInput.tsx
packages/web-domains/src/user/features/modify-user-info/components/ModifyIntroForm.tsx

fix(web-domains): 자기소개, 코멘트 validation 수정

---

packages/web-domains/src/about-me/common/apis/schema/MeetingMemberResponse.ts
packages/web-domains/src/user/features/get-user-info/components/Form/IntroInfoForm.tsx
packages/web-domains/src/user/features/modify-user-info/components/ModifyIntroForm.tsx
packages/web-domains/src/user/features/modify-user-info/containers/ModifyUserInfoContainer.tsx

fix(web-domains): 자기소개 수정 초기 데이터 불러오기

---

packages/web-domains/src/home/common/components/Layout/HomeLayout.tsx
packages/web-domains/src/home/features/gather-member/containers/GatherMemberProfileListContainer.tsx

https://www.notion.so/depromeet/Empty-View-fa7d7c09538440a9b11bd194260cf0c4?pvs=4

fix: 모임원 없을 때 EmptyView 적용

---

packages/web-domains/src/common/styles/GlobalStyles.tsx
packages/web-domains/src/home/common/components/Navigation/HomeNavigationTab.tsx

https://www.notion.so/depromeet/326f11aa3be84e408c7d0d7eb5a60bc5?pvs=4

fix: 네비게이션 하단 터치시 하이라이트 제거

---

.husky/pre-push

pre-push 시 `.next` 파일을 제거하도록 추가합니다.

chore(*): pre-push .next 파일 제거하도록 추가

---

packages/core/css-utils/src/getPadding.ts
packages/core/css-utils/src/index.ts
packages/core/sds/src/components/Button/styles.ts
packages/core/sds/src/components/ToolTip/ToolTip.tsx
packages/core/sds/src/components/ToolTip/index.ts
packages/core/sds/src/components/ToolTip/styles.ts
packages/core/sds/src/components/index.ts

```tsx
<ToolTip>툴팁내용</ToolTip>
```
https://github.com/user-attachments/assets/9397b91e-e09e-4476-a353-6c0d4b40ff9c
애니메이션이 기본적으로 적용되어 있어요. 애니메이션을 끄고 싶다면 `reduceAnimate={true}`를 사용해주세요.
`direction`이라는 인터페이스를 추가할 예정이에요.

feat(sds, css-utils): ToopTip 컴포넌트 추가 및 getPadding 유틸 메서드 추가

---

packages/web-domains/src/user/features/get-user-info/components/Form/HobbiesInfoForm.tsx
packages/web-domains/src/user/features/get-user-info/containers/GetUserHobbiesContainer.tsx

기존에 최대 3개 선택 가능에서 개수 제한 없이 선택 가능으로 변경 
[피그마](https://www.figma.com/design/K0vbFsWUNzQXl5NRGra2m9/%5BDPM%5D-3%ED%8C%80%F0%9F%A7%91%E2%80%8D%F0%9F%9A%80?node-id=2239-23270&t=sm07N3wSJLt2zw5N-4)

fix(web-domains): 모임장/원 취미 정보 입력 페이지 디자인 정의서 업데이트

---

packages/web-domains/src/answer/common/apis/schema/Question.schema.ts
packages/web-domains/src/answer/features/answer-question/components/AnswerQuestion.tsx
packages/web-domains/src/answer/features/answer-question/components/BalanceQuestion.tsx
packages/web-domains/src/answer/features/answer-question/components/MultipleDescriptiveAnswerQuestion.tsx
packages/web-domains/src/answer/features/answer-question/components/MultipleShortAnswerQuestion.tsx
packages/web-domains/src/answer/features/answer-question/containers/AnswerQuestionContainer.tsx
packages/web-domains/src/common/components/Modal/Modal.tsx

feat: 서브 타이틀 반영
