- .github/workflows/auto-merge.yml
- #2 
- ^ 잘못된 auto-merge workflow 수정
기도메타 🚀
> fix(*): auto-merge workflow 수정

- .github/labeler.yml
- .github/workflows/auto-assignee-label.yml
- .github/workflows/auto-pr.yml
https://github.com/depromeet/15th-team3-FE/pull/8
^ 에 이어서 수정합니다
> chore(*): auto-assignee-label workflow 추가

- apps/web/.eslintrc.js
- apps/web/package.json
- apps/web/tsconfig.json
- package.json
- packages/eslint-config/package.json
- packages/typescript-config/package.json
- packages/ui/package.json
- pnpm-lock.yaml
기본적으로 설정되어있는 repo라는 이름의 패키지들의 네이밍을 모두 sambad로 변경합니다.
> chore: 패키지 name 변경 repo -> sambad

- .github/labeler.yml
- .github/workflows/auto-assignee-label.yml
> fix(*): auto-assignee-label 수정

- .github/workflows/slack-notification.yml
> fix(*): Comment MSG PR 링크 수정

- .github/workflows/deploy.yml
- tools/build.sh
> feat: 배포용 workflow 추가

- .github/workflows/auto-assignee-label.yml
> fix(*): auto-assignee-label 토큰 환경변수 변경

- cspell.json
- package.json
- pnpm-lock.yaml
오탈자 방지를 위해 [스펠링 체커 익스텐션](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)을 애용하는 편인데요!
요거슬 저희 레포에서 설정하여 일관되게 다들 오탈자가 없으면 해서 추가해보았습니닷
> chore(*): cspell 의존성 및 설정 추가

- .github/workflows/deploy-integration.yml
- .github/workflows/deploy-test.yml
> feat: 배포 워크플로우 고도화

- .github/workflows/deploy-integration.yml
- .github/workflows/deploy-test.yml
> fix: 배포 워크플로우 수정

- .github/workflows/deploy-integration.yml
- .github/workflows/deploy-test.yml
> fix: workflow 수정"

- .github/workflows/deploy-integration.yml
- .github/workflows/deploy-test.yml
Reverts depromeet/15th-team3-FE#42
> chore: Revert "fix: workflow 수정""

- .github/workflows/deploy-integration.yml
> chore: workflow 수정

- .github/workflows/deploy-integration.yml
> fix: workflow 수정

- apps/web/app/page.tsx
> chore: test

- .github/workflows/deploy-integration.yml
- .github/workflows/deploy-target.yml
> refactor: workflow

- .husky/post-merge
- .husky/pre-commit
- .husky/pre-push
- apps/web/package.json
- package.json
- packages/core/eslint-config/base.js
- packages/core/sds/package.json
- packages/web-domains/package.json
- pnpm-lock.yaml
- turbo.json
husky 설정을 추가합니다.
* pre-push
husky 파일은 pre-push 만 설정하며, pre-commit은 사용하지 않습니다.
그 이유는 매 commit 마다 lint 검사를 수행하게 되면 약 2초 가량의 시간이 필요하는데, 이는 커밋 시간 자체가 오래 걸리게 되어 DX 감소 요인으로 우려됩니다.
따라서 origin push 전에 lint, type check, build를 한 번에 수행하여, DX와 개발 안정성을 가져가는 것이 좋다고 판단하여 위와 같이 작업했습니다.
또한 postinstall script 또한 작성했습니다.
@Andrevile 종오넴이 말씀해주신 postinstall이 제가 한 작업과 맞을까여? [보내주신 링크](https://withwltn.tistory.com/32)에서도 pnpm install 시 husky install 를 수행하는데 현재 이 작업은 반영되어 있습니다. 그런데 이전에 게더에서 말씀해주셨던게 이 것과는 살짝 다른 느낌이었던 걸로 기억해서 (정확히 기억이 안나긴 합니다,, 적어둘껄,,) 여쭤봅니다.
> chore(*): Husky 설정 추가

- packages/core/sds/src/components/Button/Button.tsx
- packages/core/sds/src/components/Button/index.ts
- packages/core/sds/src/components/Button/index.tsx
- packages/core/sds/src/components/Button/styles.ts
- packages/core/sds/src/components/Button/types.ts
- packages/core/sds/src/theme/borderRadius.ts
- packages/core/sds/src/theme/index.ts
- 버튼 컴포넌트 인터페이스 수정
- export 모듈 추가
- [emotion에서 소개하는 best practice](https://emotion.sh/docs/best-practices#advanced-css-variables-with-style) 중 css variable로 동적같은 정적 스타일링
- 해당 방법은 zero-runtime이라고 불리는 스타일링 라이브러리에서도 사용하는 방식입니다.
- [관련 아이클도 하나](https://www.joshwcomeau.com/css/css-variables-for-react-devs/) 첨부합니다
> fix(sds): 버튼 컴포넌트 수정

- packages/web-domains/src/common/components/Modal/Modal.tsx
> fix: 모달 close 버그 수정

- apps/web/tsconfig.json
- packages/core/sds/tsconfig.json
- packages/web-domains/tsconfig.json
별칭 절대경로를 사용할 수 있도록 tsconfig에 추가합니다.
https://depromeet-15th.slack.com/archives/C0762E1RA5T/p1722146365651649
🤔 `react-library.json` 정도에는 일괄적으로 해줄 수 있지 않을까 해서 츄라이 해보았는데 바로 되진 않아서
일단 요렇게 하고 나중에 개선해보겟습니다
> chore(web, web-domains, sds): tsconfing paths 설정

- apps/web/tsconfig.json
> fix: alias 수정

- apps/web/tsconfig.json
아까 반영한 tsconfig 빌드 되었던거 캐시때문이었나봅니다..
이렇게 해야할거같아요.
> fix: tsconfig

- packages/core/sds/src/components/Badge/Badge.tsx
- packages/core/sds/src/components/Badge/index.ts
- packages/core/sds/src/components/Badge/styles.ts
- packages/core/sds/src/components/index.ts
> feat(sds): Badge 컴포넌트

- apps/web/tsconfig.json
- packages/core/sds/src/components/Badge/Badge.tsx
- packages/core/sds/src/components/Badge/styles.ts
- packages/core/sds/src/components/Button/styles.ts
- packages/core/sds/src/components/Icon/Icon.tsx
- packages/core/sds/src/components/TextButton/TextButton.tsx
- packages/core/sds/src/components/Typography/Txt.tsx
- packages/core/sds/tsconfig.json
sds 절대 경로 alias 추가하고, badge 스타일 일부 수정합니다~
> fix(*): sds 절대경로 alias 추가

- packages/core/eslint-config/base.js
- packages/core/sds/package.json
- packages/core/sds/src/components/SegmentedControl/Item.tsx
- packages/core/sds/src/components/SegmentedControl/SegmentedControl.tsx
- packages/core/sds/src/components/SegmentedControl/constants.ts
- packages/core/sds/src/components/SegmentedControl/context.ts
- packages/core/sds/src/components/SegmentedControl/index.ts
- packages/core/sds/src/components/SegmentedControl/styles.ts
- packages/core/sds/src/components/index.ts
- packages/core/sds/src/hooks/index.ts
- packages/core/sds/src/hooks/indext.ts
- packages/core/sds/src/hooks/useCallbackRef.ts
- packages/core/sds/src/hooks/useComposedRefs.ts
- packages/core/sds/src/hooks/useControllableState.ts
- packages/core/sds/src/hooks/useResizeObserver.ts
- packages/core/sds/src/utils/buildContext.tsx
- packages/core/sds/src/utils/composeEventHandlers.ts
- packages/core/sds/src/utils/index.ts
- pnpm-lock.yaml
controlled, uncontrolled 모두 동작합니다.
```tsx
<SegmentedControl value={...} onValueChange={...}>
<SegmentedControl.Item value="temp1">temp1</SegmentedControl.Item>
<SegmentedControl.Item value="temp2">temp2</SegmentedControl.Item>
<SegmentedControl.Item value="temp3">temp3</SegmentedControl.Item>
</SegmentedControl>
```
https://github.com/user-attachments/assets/6b43baae-4244-4299-aff6-830dbb30dc54
redix에서 참고한 것이라 주석으로 링크 남겨두었습니다 🙇🏻‍♀️
> feat(sds): SegmentedControl 컴포넌트 추가

- apps/web/tsconfig.json
> fix: sds tsconfig alias 수정

- apps/web/.gitignore
- apps/web/package.json
- package.json
- turbo.json
> feat: localhost self signed https 적용

- packages/web-domains/tsconfig.json
> fix: web-domains alias

- packages/web-domains/src/common/styles/GlobalStyles.tsx
- pnpm-lock.yaml
> fix(web-domains): global-styles 수정

- packages/web-domains/.eslintrc.js
- packages/web-domains/src/common/components/KakaoShare/KakaoShare.tsx
- packages/web-domains/src/common/components/KakaoShare/KakaoShareModal.tsx
- packages/web-domains/src/common/components/KakaoShare/generateKakaoShare.utils.ts
> refactor(web-domains): 카카오톡 공유하기 모달 interface 수정

- packages/web-domains/src/common/components/KakaoShare/generateKakaoShare.utils.ts
mobileWebUrl 옵션도 추가하여, 모바일 공유하기도 환경별 대응을 하도록 합니다.
> fix: 모바일 url 대응

- apps/web/app/layout.tsx
- apps/web/package.json
- pnpm-lock.yaml
- turbo.json
next third party를 이용해서 GA를 추가합니다.
https://nextjs.org/docs/app/building-your-application/optimizing/third-party-libraries#google-analytics
> feat(apps/web): GA4 Tag 추가

- packages/web-domains/src/result/features/main/components/SelectedDataCard/styles.ts
flex 없어서 수직으로 쌓여서 보이는 부분을 수정합니다~!
바로 depoly 한번더 가겠습니다~!
> fix(web-domains): 결과 페이지에서 CountByMemberList 컴포넌트 display 수정

- packages/web-domains/src/home/features/gather-member/containers/GatherMemberProfileListContainer.tsx
> fix: 모임원 목록 bottom padding 추가

- .husky/pre-push
- packages/core/eslint-config/base.js
- packages/web-domains/src/about-me/features/containers/ScreenContainer.tsx
- packages/web-domains/src/result/common/components/Layout/BaseLayout.tsx
- packages/web-domains/src/result/features/list/components/MemberListItem/styles.ts
- packages/web-domains/src/result/features/list/containers/AnswerListContainer.tsx
- packages/web-domains/src/result/features/list/containers/MostSelectedListContainer.tsx
- packages/web-domains/src/result/features/list/containers/SelectedSameListContainer.tsx
- packages/web-domains/src/result/features/main/screens/ResultMainScreen.tsx
- packages/web-domains/src/result/features/statistics/containers/StatisticsContainer.tsx
- packages/web-domains/src/result/features/statistics/screens/StatisticsScreen.tsx
result, about 도메인 (담당) 액션바 추가했습니다 🦅
> feat(web-domains): result, about 도메인 액션바 추가

- packages/web-domains/src/home/features/floating-button/components/AlreadyAnsweredQuestionModal.tsx
- packages/web-domains/src/home/features/notification/components/ArrivedQuestionNotification.tsx
- packages/web-domains/src/home/features/notification/components/ExpiredQuestionNotification.tsx
- packages/web-domains/src/home/features/notification/components/SelectedTargetMemberNotification.tsx
- packages/web-domains/src/home/features/notification/containers/NotificationContainer.tsx
https://www.notion.so/depromeet/83237e9f2b874e1f8fb059644fed0312?pvs=4
> fix: 모달 일러스트 제거

- apps/web/app/[meetingId]/user/modify/page.tsx
- packages/web-domains/src/user/common/api/mutations/useModifyUserInfo.ts
- packages/web-domains/src/user/common/api/schema/MeetingMemberResponse.ts
- packages/web-domains/src/user/features/get-user-info/containers/GetUserBasicInfoContainer.tsx
- packages/web-domains/src/user/features/get-user-info/containers/GetUserExtraInfoContainer.tsx
- packages/web-domains/src/user/features/modify-user-info/components/ModifyIntroForm.tsx
- packages/web-domains/src/user/features/modify-user-info/containers/ModifyUserInfoContainer.tsx
- packages/web-domains/src/user/features/modify-user-info/containers/ModifyUserIntroContainer.tsx
- packages/web-domains/src/user/features/modify-user-info/services/useModifyUserInfoService.ts
- packages/web-domains/src/user/index.ts
- packages/web-domains/src/user/screens/ModifyUserInfoScreen.tsx
> feat(web-domains): 유저 정보 수정

- packages/web-domains/src/about-me/features/containers/AnsweredQuestionsContainer.tsx
- packages/web-domains/src/home/features/previous-question/components/PreviousQuestion/PreviousQuestionItem.tsx
- packages/web-domains/src/home/features/previous-question/containers/PreviousQuestionListContainer.tsx
> fix: 유저 질문 답변 목록 에러 수정

- packages/web-domains/src/answer/common/components/Layout/AnswerOpeningLayout.tsx
- packages/web-domains/src/answer/features/floating-button/components/AnswerButton.tsx
- packages/web-domains/src/answer/features/floating-button/components/HomeButton.tsx
- packages/web-domains/src/answer/features/floating-button/components/ShareButton.tsx
- packages/web-domains/src/answer/features/floating-button/components/StartButton.tsx
- packages/web-domains/src/answer/features/progressing-question/components/QuestionInfo.tsx
- packages/web-domains/src/answer/features/progressing-question/containers/ProgressingQuestionContainer.tsx
- https://www.notion.so/depromeet/35964e2e6b424e6091d561c353c2fb68?pvs=4
- https://www.notion.so/depromeet/be36f2bb503c4bd68a1203ae7e526bc7?pvs=4
> fix(web-domains): 답변 페이지 프로필 이미지, 버튼 사이즈 수정

- packages/web-domains/src/relay-question/features/select-relay-question/components/Question/Question.styles.ts
- packages/web-domains/src/relay-question/features/select-relay-question/components/Question/Question.tsx
- packages/web-domains/src/relay-question/features/select-relay-question/components/QuestionDetail/QuestionDetail.tsx
- packages/web-domains/src/relay-question/features/select-relay-question/components/Questioner/Questioner.tsx
- packages/web-domains/src/relay-question/features/select-relay-question/components/QuestionerDetail/QuestionerDetail.tsx
- packages/web-domains/src/relay-question/features/select-relay-question/containers/ContentContainer/ContentContainer.tsx
- packages/web-domains/src/relay-question/features/select-relay-question/containers/RandomPickContainer/RandomPickContainer.tsx
- packages/web-domains/src/relay-question/features/share-group/components/CurrentQuestionInfo/CurrentQuestionInfo.styles.ts
- packages/web-domains/src/relay-question/features/share-group/components/CurrentQuestionInfo/CurrentQuestionInfo.tsx
- packages/web-domains/src/relay-question/features/share-group/containers/CurrentRelayQuestionCountContainer/CurrentRelayQuestionCountContainer.styles.ts
- packages/web-domains/src/relay-question/features/share-group/containers/CurrentRelayQuestionCountContainer/CurrentRelayQuestionCountContainer.tsx
- packages/web-domains/src/relay-question/features/share-next-questioner/containers/ShareNextQuestionerContainer/ShareNextQuestionerContainer.styles.ts
- packages/web-domains/src/relay-question/features/share-next-questioner/containers/ShareNextQuestionerContainer/ShareNextQuestionerContainer.tsx
- packages/web-domains/src/relay-question/features/start-relay-question/components/Profile/Profile.tsx
- packages/web-domains/src/relay-question/features/start-relay-question/containers/StartQuestionContainer/StartQuestionContainer.tsx
> refactor(relay-quesiton): word break, object-fit 등 자잘한 CSS 이슈 수정

- packages/web-domains/src/home/features/floating-button/components/StartRelayQuestionButton.tsx
- packages/web-domains/src/home/features/floating-button/containers/FloatingButtonContainer.tsx
- packages/web-domains/src/home/features/floating-button/services/useFloatingButtonService.ts
- packages/web-domains/src/home/features/notification/containers/NotificationContainer.tsx
- packages/web-domains/src/home/features/notification/services/useNotificationService.ts
- packages/web-domains/src/home/features/progressing-question/components/QuestionInfo/InActiveQuestion.tsx
- packages/web-domains/src/home/features/progressing-question/containers/ProgressingQuestionContainer.tsx
- packages/web-domains/src/home/features/progressing-question/services/useProgressingQuestionService.tsx
> fix: 모임장 생성시 질문 시작안되도록 변경

- packages/web-domains/src/answer/features/answer-question/components/BalanceQuestion.tsx
https://github.com/user-attachments/assets/7d669d4a-fe43-4b00-a758-bc6a5731b84a
> fix(web-domains): 질문 선택 버튼 스타일 수정

- packages/web-domains/src/result/features/list/components/MemberList/MemberList.tsx
> fix(web-domains): answers 리스트 페이지에서 프로필 클릭 시 잘못된 링크 수정

- packages/web-domains/src/about-me/features/containers/styles.ts
|:--:|:--:|
| ![image](https://github.com/user-attachments/assets/e4535ac3-a29d-41c8-b0bc-f533853bd777) | ![image](https://github.com/user-attachments/assets/3826c168-fce1-484f-a794-4aa5c20f1efc) |
스미마셍
> fix(web-domains): 손 흔들기 버튼 최대 너비 수정

- packages/web-domains/src/home/common/apis/schema/Notification.schema.ts
- packages/web-domains/src/home/features/notification/containers/AlarmListContainer.tsx
- packages/web-domains/src/home/features/notification/services/useAlarmListService.ts
> fix: 알림 인사하기 수락 OR 거절 버튼 상태에 따른 노출 처리 및 쿼리 invalidation

- packages/web-domains/src/result/features/main/containers/MostAnsweredContainer.tsx
> fix: 아무도 답하지 않았을 때 결과페이지 대응

- packages/web-domains/src/new-meeting/features/get-meeting-info/components/Checkbox/CheckboxGroupImpl.tsx
- packages/web-domains/src/new-meeting/features/get-meeting-info/components/Checkbox/styles.ts
- packages/web-domains/src/new-meeting/features/get-meeting-info/components/GetMeetingInfo/GetMeetingInfo.tsx
- packages/web-domains/src/new-meeting/features/get-meeting-info/components/Radio/styled.ts
- packages/web-domains/src/user/features/get-user-info/components/Checkbox/CheckboxGroupImpl.tsx
- packages/web-domains/src/user/features/get-user-info/components/Checkbox/styles.ts
- packages/web-domains/src/user/features/get-user-info/components/Form/BasicInfoForm.tsx
- packages/web-domains/src/user/features/get-user-info/components/Form/ExtraInfoForm.tsx
- packages/web-domains/src/user/features/get-user-info/components/Form/HobbiesInfoForm.tsx
- packages/web-domains/src/user/features/get-user-info/components/Form/IntroInfoForm.tsx
- packages/web-domains/src/user/features/get-user-info/components/Radio/styles.ts
- packages/web-domains/src/user/features/get-user-info/components/TextInput/TextInput.tsx
- packages/web-domains/src/user/features/modify-user-info/components/ModifyIntroForm.tsx
- packages/web-domains/src/user/features/select-user-role/components/RoleRadioButton.tsx
> fix(web-domains): validation 추가 및 자잘한 에러 수정

- packages/web-domains/src/home/features/floating-button/services/useFloatingButtonService.ts
- packages/web-domains/src/home/features/notification/services/useNotificationService.ts
- packages/web-domains/src/home/features/progressing-question/services/useProgressingQuestionService.tsx
> fix: 모임 생성시 모임원 있어도 진행 못하는 이슈 수정

- packages/web-domains/src/new-meeting/features/new-meeting-closing/components/Button/InviteLinkShareButton.tsx
- packages/web-domains/src/new-meeting/features/new-meeting-closing/components/Button/ShareKakaoButton.tsx
> fix(web-domains): 모임 초대코드 공유 링크 수정

- packages/web-domains/src/common/apis/queries/useGetMeetingName.ts
- packages/web-domains/src/participate-meeting/screens/ParticipateClosingScreen.tsx
> refactor(progressing-question): 이미 가입된 모임 초대 시 홈으로 리다이렉트 하도록 변경

- packages/web-domains/src/home/common/hooks/useSetCurrentMeeting.ts
- packages/web-domains/src/user/features/get-user-info/services/useMeetingMemberService.ts
> fix: 모임생성시 생성된 모임으로 이동

- packages/web-domains/src/user/features/get-user-info/components/Form/IntroInfoForm.tsx
> fix: 모임 생성 중복생성 방지

- packages/web-domains/src/home/features/floating-button/components/StartRelayQuestionButton.tsx
> fix: 릴레이 질문 시작 플로팅 버튼 링크 수정

- packages/web-domains/src/home/common/apis/queries/useGetNotification.ts
- packages/web-domains/src/home/common/hooks/useSetCurrentMeeting.ts
- packages/web-domains/src/home/features/notification/services/useAlarmListService.ts
- packages/web-domains/src/home/features/notification/services/useNotificationService.ts
- packages/web-domains/src/home/features/previous-question/containers/PreviousQuestionListContainer.tsx
- packages/web-domains/src/home/features/previous-question/services/usePreviousQuestionListService.tsx
- packages/web-domains/src/home/features/progressing-question/containers/ProgressingQuestionContainer.tsx
- packages/web-domains/src/user/features/get-user-info/services/useCreateMeetingService.ts
> fix: QA 이슈 반영

- packages/web-domains/src/home/common/hooks/useSetCurrentMeeting.ts
- packages/web-domains/src/new-meeting/features/new-meeting-closing/containers/NewMeetingButtonContainer.tsx
- packages/web-domains/src/user/features/get-user-info/services/useCreateMeetingService.ts
- packages/web-domains/src/user/features/get-user-info/services/useMeetingMemberService.ts
> fix: meeting

- packages/web-domains/src/user/features/get-user-info/components/Form/IntroInfoForm.tsx
- packages/web-domains/src/user/features/get-user-info/services/useMeetingMemberService.ts
> fix: 중복생성 방지

- packages/web-domains/src/answer/features/comment/services/useCommentService.tsx
- packages/web-domains/src/new-meeting/features/new-meeting-closing/components/Button/InviteLinkShareButton.tsx
- packages/web-domains/src/new-meeting/features/new-meeting-closing/components/Button/ShareKakaoButton.tsx
> fix(home): 릴레이 질문 마지막으로 답변하고 바로 다음 질문 시작할 때 CTA 버튼 카운트 다운으로 보이는 이슈

- packages/web-domains/src/home/features/notification/containers/AlarmListContainer.tsx
> fix(AlaramListContainer): 인사 무시하기 후 알림 footer가 남아있던 오류 해결

- packages/core/sds/src/components/Button/Button.tsx
loading 시 따닥을 방지하기 위해 disabled 처리 합니다.
> feat(sds): Button loading 시 disabled 처리

- packages/web-domains/src/answer/features/answer-question/components/MultipleDescriptiveAnswerQuestion.tsx
- packages/web-domains/src/answer/features/answer-question/components/MultipleShortAnswerQuestion.tsx
- packages/web-domains/src/result/common/components/HeaderBanner/HeaderBanner.tsx
- packages/web-domains/src/result/features/main/components/SelectedDataCard/Comment.tsx
- packages/web-domains/src/result/features/main/components/SelectedDataCard/styles.ts
- packages/web-domains/src/result/features/statistics/components/RankList/Item.tsx
- 여백이나 work-break 넣어주었습니다.
- 답변 선택을 위한 버튼들 스타일 수정했습니다.
> fix(web-domains): 텍스트 관련 레이아웃 문제 수정

- packages/web-domains/src/answer/features/answer-question/components/MultipleDescriptiveAnswerQuestion.tsx
- packages/web-domains/src/answer/features/answer-question/components/MultipleShortAnswerQuestion.tsx
- https://github.com/depromeet/15th-team3-FE/pull/183 에서 누락된 답변 버튼 cursor 스타일을 추가합니다.
> fix(web-domains): 질문 답변 버튼 cursor 스타일 누락 수정

- packages/web-domains/src/about-me/features/components/IntroduceBox/IntroduceBox.tsx
> fix(web-domains): 자기소개에 `\n` 포함 시 줄바꿈 되어 렌더링될 수 있도록 수정

- packages/web-domains/src/home/features/my-profile/components/AboutMe.tsx
> fix(web-domains): 자기소개 empty 처리 조건 보강

- packages/core/sds/src/components/Skeleton/styles.ts
- packages/web-domains/src/answer/features/progressing-question/components/Skeleton/ProgressingQuestionContainerSkeleton.tsx
- packages/web-domains/src/answer/features/progressing-question/containers/ProgressingQuestionContainer.tsx
- packages/web-domains/src/answer/features/progressing-question/services/useProgressingQuestionService.tsx
- packages/web-domains/src/home/common/hooks/useSetCurrentMeeting.ts
- packages/web-domains/src/home/features/previous-question/components/Skeleton/PreviousQuestionListContainerSkeleton.tsx
- packages/web-domains/src/home/features/previous-question/containers/PreviousQuestionListContainer.tsx
- packages/web-domains/src/home/features/previous-question/services/usePreviousQuestionListService.tsx
- packages/web-domains/src/relay-question/features/select-relay-question/components/Skeleton/NextQuestionerListSkeleton.tsx
- packages/web-domains/src/relay-question/features/select-relay-question/components/Skeleton/QuestionListSkeleton.tsx
- packages/web-domains/src/relay-question/features/select-relay-question/containers/ContentContainer/ContentContainer.tsx
- packages/web-domains/src/relay-question/features/select-relay-question/containers/RandomPickContainer/RandomPickContainer.tsx
> feat(*): 로딩 시 스켈레톤 적용

- README.md
> chore(*): README.md 추가

- .github/labeler.yml
> chore(*): labeler 워크플로우에 refactor 라벨 추가

- packages/web-domains/src/result/common/components/Layout/BaseLayout.tsx
|:--:|:--:|
| ![IMG_6314 PNG](https://github.com/user-attachments/assets/6d5b78a3-96bf-42bc-8dde-14bd22709ff8) | ![image](https://github.com/user-attachments/assets/76eccdc9-c2cb-4ba4-8c66-ef7111661ae4) |
> fix(web-domains): 결과 페이지 하단 여백 채우도록 수정

- packages/web-domains/src/about-me/features/components/HobbyList/HobbyList.tsx
제곧내..~
https://depromeet-15th.slack.com/archives/C07HQDR5NHG/p1725959093174319
> fix(web-domains): 마이프로필 내 취미 리스트 레이블 텍스트 수정

- packages/web-domains/src/result/common/components/Layout/BaseLayout.tsx
- packages/web-domains/src/result/features/main/components/SelectedDataCard/Content.tsx
- packages/web-domains/src/result/features/main/containers/MostAnsweredContainer.tsx
> fix(web-domains): 결과 페이지 프로필 개수 버그 수정

- packages/web-domains/src/result/common/components/Layout/BaseLayout.tsx
> fix(web-domains): 통계 페이지 background-color 적용 레벨 수정

- packages/web-domains/src/user/features/modify-user-info/components/ModifyIntroForm.tsx
- packages/web-domains/src/user/features/modify-user-info/containers/ModifyUserInfoContainer.tsx
introduction에 대한 정보를 수정 페이지에서 가져오지 않아서 추가하도록 변경하였습니다.
> fix(web-domains): 유저 정보 수정 자기소개 정보 불러오기

- packages/web-domains/src/new-meeting/features/get-meeting-info/components/Checkbox/CheckboxLabel.tsx
- packages/web-domains/src/user/features/get-user-info/components/Checkbox/CheckboxLabel.tsx
- packages/web-domains/src/user/features/get-user-info/components/Radio/RadioLabel.tsx
> fix(web-domains): Checkbox selected 폰트 사이즈 변경

- packages/web-domains/src/user/features/oauth-kakao-login/containers/LoginContainer.tsx
|:--:|:--:|
|![Simulator Screen Shot - iPhone 12 mini - 2024-09-13 at 03 47 44](https://github.com/user-attachments/assets/9a5210f7-e370-4842-b5f5-f49d55e4f2c9)|![Simulator Screen Shot - iPhone 12 mini - 2024-09-13 at 03 50 52](https://github.com/user-attachments/assets/fa732ea9-cedc-4bcb-b502-dc47a32bcccc)|
> fix(web-domains): 로그인 디자인 정의서 업데이트

- packages/web-domains/src/home/features/gather-member/components/GatherMemberSearch/GatherMemberSearchInput.tsx
https://www.notion.so/depromeet/bd5d3265292844d395a165437cc580c0?pvs=4
> fix: 검색 input focus borderColor

- packages/web-domains/src/answer/common/apis/queries/useGetQuestion.ts
- packages/web-domains/src/answer/common/apis/schema/Question.schema.ts
- packages/web-domains/src/answer/features/answer-question/containers/AnswerQuestionContainer.tsx
- packages/web-domains/src/answer/screens/AnswerQuestionScreen.tsx
> fix: 답변 서브타이틀

- packages/web-domains/src/about-me/features/components/HobbyList/styles.ts
|:--:|:--:|
| ![image](https://github.com/user-attachments/assets/8a3e956c-f1ca-4a73-8c30-df29225dbea5) | ![image](https://github.com/user-attachments/assets/5c263b77-0bf5-4f7d-8454-dab8d0c84ef6)| 
정확하게 하려면 부모 컨테이너에서 역마진으로 잘라야할 거 같긴 한데 딱 맞게 들어가는 케이스는 거의 없을 것 같아 우선 빠르게 대응해보았습니다.
> fix(web-domains): HobbyList 레이아웃 수정

- packages/web-domains/src/home/common/apis/schema/Notification.schema.ts
- packages/web-domains/src/home/features/notification/containers/AlarmListContainer.tsx
> feat: 알림 타입 추가

- README.md
> chore(*): README에 Tech Stack 추가

- packages/web-domains/src/answer/features/comment/components/CommentInput.tsx
- packages/web-domains/src/answer/features/progressing-question/containers/ProgressingQuestionContainer.tsx
- packages/web-domains/src/answer/features/progressing-question/services/useProgressingQuestionService.tsx
- packages/web-domains/src/user/common/api/mutations/useModifyUserInfo.ts
> refactor(*): 코멘트 input padding 보정 및 질문 생성 후 바로 답변하기 페이지 이동시 Skeleton

- packages/web-domains/src/home/features/gather-member/services/useGatherMemberProfileListService.tsx
> fix: hotfix
